
url: ""
baseurl: ""
title: "Sohan Prabhu"
description: "Project blog"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: null
  smart_quotes: false
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"