
url: ""
baseurl: ""
title: "Sohan Prabhu"
description: "Project blog"
markdown: kramdown
markdown: kramdown
kramdown:
  input: kramdown
  math_engine: mathjax
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"